[tool.black]
target-version = ["py39", "py310"]

[tool.isort]
profile = "black"
combine_as_imports = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
force_sort_within_sections = true
forced_separate = ["tests"]
include_trailing_comma = true
indent = "    "
known_first_party = ["custom_components", "tests"]
multi_line_output = 3
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
src_paths = ["custom_components", "tests"]
use_parentheses = true

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "skip"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
addopts = "--cov=custom_components"
testpaths = [
  "tests",
]
