[tool.isort]
profile = "black"
combine_as_imports = true
forced_separate = ["tests"]
indent = "    "
known_first_party = ["custom_components", "tests"]
force_sort_within_sections = true
include_trailing_comma = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
src_paths = ["custom_components", "tests"]

[tool.pytest.ini_options]
addopts = "--cov=custom_components"
testpaths = [
  "tests",
]
