---
name: 'Validate'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
jobs:
  hacs:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'hacs/action@main'
        with:
          category: 'integration'
          ignore: 'brands'
  home-assistant:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'home-assistant/actions/hassfest@master'
